services:
  - type: web
    name: kvant-messenger
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "postgresql://postgres:[ЗАМЕНИТЕ_НА_ВАШ_ПАРОЛЬ]@db.uivqoiqrcaqralwxwsxa.supabase.co:5432/postgres"
      - key: JWT_SECRET
        generateValue: true
      - key: VAPID_PUBLIC_KEY
        value: BDd3hdZyXYibDIQqf_XtardGtmqaELw5_aO6WFWKFT8iLp4IcrIanZqOCsJrKlOh0BchoGdm8mFh9TbT3kRXtA0
      - key: VAPID_PRIVATE_KEY
        value: WlsEpZoei1Rcrtrzve2PmL9IoFbNalQ6JiEMQmCj2lk

# Удаляем старую базу данных Render
